Canopen system interface
ros-industrial/ros2_canopen pull request #33
Opened 2022-08-05 08:24 UTC by destogl

This is a overview PR with integration of ros2_canopen and ros2_control. The PR will be divided into smaller PR to make review easier. Concrete PR will be referenced below.

- Updates of the `DeviceManager` to support its use as library
- Updates with automated tests of `DeviceManager`
- Addition of `canopen_ros2_control::CanopenSystem`
- Addition of  `canopen_ros2_controllers::CanopenController`
- Addition of `canopen_ros2_control::CIA402System`
- Usage examples for `CIA402System`

2022-08-08 08:44 UTC, ipa-cmh commented
Regarding the state machine matching I would propose the following:
![image](https://user-images.githubusercontent.com/51296695/183367564-71db9b68-f956-4c20-ae68-290e09a2a0dd.png)

**Activating** should call *handleInit()*. This will put the motion controller into Operation Enabled state and executed the configured homing sequence. Then it should call *enterModeAndWait(MotorBase::??)* with ?? either No_Mode or the Mode user configured during Inactive.

**Deactivating** should set call *enterModeAndWait(MotorBase::No_Mode)* and then *handleShutdown()*.

In this, we do not use QuickStop which is usually used for stopping the device during operation fast. This does only Stop the movement and usually slam in the breaks. It does not disable torque. I am not sure, how this would be integrated into the ros2_control interface.

2022-08-12 09:27 UTC, ipa-cmh commented
There is some major restructuring being done in #34.
After some analysis, it seems that it is easier to rebase this PR onto #34. 
It is mainly a renaming and CMakeLists.txt merge issue.

This is the result of the rebase, if possible please check: https://github.com/ipa-cmh/ros2_canopen/tree/canopen-system-interface

I am planning to do tidy up the device interface as well, but I will wait until this PR is merged.

2022-08-17 08:12 UTC, ipa-cmh requested changes
I did an intial review. Generally it looks good, I suppose we just need to remove the tests from CMakeLists.txt for now.

2022-08-17 08:12 UTC, hellantos commented on canopen_core/src/device_manager.cpp
> +
Makes sense to me. The information is passed in via URDF when using the system interface right.

2022-08-17 08:12 UTC, hellantos commented on canopen_proxy_driver/CMakeLists.txt
> +  find_package(launch_testing_ament_cmake)
Honestly, theses tests are pretty buggy for the moment and pass only every other time. They also require vcan0 to be up, which will break CI.

2022-08-17 08:12 UTC, hellantos commented on canopen_proxy_driver/CMakeLists.txt
> +  add_launch_test(test/test_sdo.py)
```suggestion

```

2022-09-09 18:12 UTC, destogl commented on canopen_core/src/device_manager.cpp
> +
yes

2022-09-09 18:13 UTC, destogl commented on .gitignore
> +#**/master.dcf
```suggestion
**/master.dcf
```

2022-09-09 18:16 UTC, destogl commented
@livanov93 do we need all of those `*.dcf` files?

2022-09-12 13:46 UTC, ipa-cmh requested changes

2022-09-12 13:46 UTC, ipa-cmh commented on canopen_core/CMakeLists.txt
> +  device_manager
This should proably be device_container.

2022-09-12 13:48 UTC, ipa-cmh commented
This PR breaks compatability with foxy and galactic, as far as I can see. I suppose there is no way of having them supported easily.
For me this means, we I need to split of foxy and galactic support into a seperate branch.

2022-09-13 07:40 UTC, livanov93 commented
> This PR breaks compatability with foxy and galactic, as far as I can see. I suppose there is no way of having them supported easily. For me this means, we I need to split of foxy and galactic support into a seperate branch.

We will need split branches for separate `ROS_DISTRO`s because the same approach is used in [`ros2_control`](https://github.com/ros-controls/ros2_control/branches).

2022-09-13 07:48 UTC, borongyuan commented
> > This PR breaks compatability with foxy and galactic, as far as I can see. I suppose there is no way of having them supported easily. For me this means, we I need to split of foxy and galactic support into a seperate branch.
> 
> We will need split branches for separate `ROS_DISTRO`s because the same approach is used in [`ros2_control`](https://github.com/ros-controls/ros2_control/branches).

This is reasonable. How to migrate Hardware Components from Foxy to Galactic is explained [here](https://control.ros.org/master/doc/ros2_control/hardware_interface/doc/hardware_components_userdoc.html#migration-from-foxy-to-galactic).

2022-09-13 09:24 UTC, ipa-cmh commented
Alright. I have create seperate branches for foxy, galactic, humble. I'd host rolling in master. I have reserved some lab time tomorrow morning for testing this with a the trinamic pd42 device and maybe the prbt.

2022-09-13 09:27 UTC, ipa-cmh commented
@livanov93 @destogl I would be okay with only supporting ros2_control in humble onwards. Foxy is EOL in about 8 month and Galactic in November anyways.

2022-09-13 19:54 UTC, destogl commented
> nly supporting ros2_control in humble onwards. Foxy is EOL in about 8 month and Galactic in November anyways.

yes of course! This saves us some time for sure.

2022-09-13 19:55 UTC, destogl commented on canopen_core/CMakeLists.txt
> +  device_manager
```suggestion
  device_container
```

2022-09-15 11:12 UTC, ipa-cmh approved these changes

2022-09-15 13:00 UTC, ipa-cmh commented
@destogl @livanov93
Finished tests and did some updates to integrate better with the current launch infrastructure.
You can find a few changes in https://github.com/StoglRobotics-forks/ros2_canopen/pull/6

2022-09-15 13:04 UTC, livanov93 commented
@ipa-cmh I did part of that in the ros-industrial/ros2_canopen@02c7090. Can you rebase in StoglRobotics-forks/ros2_canopen#6?

2022-09-15 13:05 UTC, livanov93 commented
> @destogl @livanov93 Finished tests and did some updates to integrate better with the current launch infrastructure. You can find a few changes in [StoglRobotics-forks#6](https://github.com/StoglRobotics-forks/ros2_canopen/pull/6)

@ipa-cmh I did part of that in the ros-industrial/ros2_canopen@02c7090. Can you rebase in StoglRobotics-forks/ros2_canopen#6?

2022-09-15 13:25 UTC, ipa-cmh commented
@livanov93 done. basically this moves testing specific device files into the canopen_tests folder.

2022-09-15 22:21 UTC, destogl commented
@ipa-cmh @livanov93 I have added a short documentation about testing this interface.

To not block this PR any longer I will add a longer documentation into a separate PR (page: https://ros-industrial.github.io/ros2_canopen/system-interface.html) in the next day or two.

2022-09-16 05:05 UTC, merged

2023-02-01 03:50 UTC, jclinton830 commented
Hi! Are there any plans on adding detailed documentation or a user guide on how to use this ROS2 control system interface feature? 

I have checked the official documentation provided but it seems to be empty for now. https://ros-industrial.github.io/ros2_canopen/manual/user-guide/operation/ros2-control-interface.html