Add formatters as used in ros2_control framework.
ros-industrial/ros2_canopen pull request #61
Opened 2022-09-30 12:41 UTC by destogl

Adding code formatters as used by Control WG (in ros2_control-related repositories).

This adds `pre-commit` support that simplifies execution of formatter before each commit and results generally in more clenar code and contributions."

The same formatters and linters are integrated into CI and running on each PR.

2022-10-03 08:07 UTC, livanov93 approved these changes

2022-10-06 10:13 UTC, ipa-cmh reviewed
I have been testing this.
A few things I do not like are:
* No line breaks after braces when there is only one statement.  Change to allman
* No reflow of comments will lead to a lot of manual work

2022-10-06 10:13 UTC, ipa-cmh commented on .clang-format
> +IncludeBlocks: Preserve
```suggestion
Language: Cpp
BasedOnStyle: Google

AccessModifierOffset: -4
AlignAfterOpenBracket: AlwaysBreak
BreakBeforeBraces: Allman
ColumnLimit: 100
ConstructorInitializerIndentWidth: 0
ContinuationIndentWidth: 4
IndentWidth: 4
TabWidth: 4
DerivePointerAlignment: false
PointerAlignment: Middle
ReflowComments: true
IncludeBlocks: Preserve
```

2022-10-06 10:30 UTC, ipa-cmh commented on .pre-commit-config.yaml
> +        language: system
```suggestion
  #- repo: local
    #hooks:
      #- id: ament_copyright
        #name: ament_copyright
        #description: Check if copyright notice is available in all files.
        #stages: [commit]
        #entry: ament_copyright
        #language: system
```

2022-10-06 11:07 UTC, ipa-cmh commented on .pre-commit-config.yaml
> +        exclude: CHANGELOG\.rst|\.(svg|pyc|drawio)$
```suggestion
        exclude: CHANGELOG\.rst|\.(svg|pyc|drawio|dcf|eds)$
```

2022-10-06 11:45 UTC, ipa-cmh requested changes
A few changes. Generally to make using pre-commit easier. We'll push the manual code changes over time and enable other formatters.

2022-10-06 11:45 UTC, hellantos commented on .pre-commit-config.yaml
> +        language: system
```suggestion
  # - repo: local
  #   hooks:
  #     - id: ament_cppcheck
  #       name: ament_cppcheck
  #       description: Static code analysis of C/C++ files.
  #       stages: [commit]
  #       entry: ament_cppcheck
  #       language: system
  #       files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$

  # Maybe use https://github.com/cpplint/cpplint instead
  # - repo: local
  #   hooks:
  #     - id: ament_cpplint
  #       name: ament_cpplint
  #       description: Static code analysis of C/C++ files.
  #       stages: [commit]
  #       entry: ament_cpplint
  #       language: system
  #       files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  #       args: ["--linelength=100", "--filter=-whitespace/newline"]

  # Cmake hooks
  # - repo: local
  #   hooks:
  #     - id: ament_lint_cmake
  #       name: ament_lint_cmake
  #       description: Check format of CMakeLists.txt files.
  #       stages: [commit]
  #       entry: ament_lint_cmake
  #       language: system
  #       files: CMakeLists\.txt$

  # Copyright
  # - repo: local
  #   hooks:
  #     - id: ament_copyright
  #       name: ament_copyright
  #       description: Check if copyright notice is available in all files.
  #       stages: [commit]
  #       entry: ament_copyright
  #       language: system

```

2022-10-06 11:45 UTC, hellantos commented on .pre-commit-config.yaml
> +        language: system
Disable ament_copyright, ament_lint_cmake, ament_cpplint and ament_cppcheck for now as they require substancial manual changes-

2022-10-06 11:45 UTC, hellantos commented on .pre-commit-config.yaml
> +      args: ["--ignore=E501"]
Disable pep257 because it does not work with python 3.10. Disable falke8 as it requires many manual changes to pass.
```suggestion
  # PEP 257
  # - repo: https://github.com/FalconSocial/pre-commit-mirrors-pep257
  #   rev: v0.3.3
  #   hooks:
  #   - id: pep257
  #     args: ["--ignore=D100,D101,D102,D103,D104,D105,D106,D107,D203,D212,D404"]

  # - repo: https://github.com/pycqa/flake8
  #   rev: 5.0.4
  #   hooks:
  #   - id: flake8
  #     args: ["--ignore=E501"]
```

2022-10-06 11:51 UTC, hellantos commented on .github/workflows/ci-ros-lint.yml
> +name: ROS Lint
I'd not run this for now.

2022-10-19 06:17 UTC, closed without merging

2022-10-19 06:34 UTC, ipa-cmh commented
Merged in manually