[WIP] Motor profile for ros2_control
ros-industrial/ros2_canopen pull request #65
Opened 2022-10-05 09:42 UTC by livanov93

# Description
TODO

2022-10-11 12:58 UTC, ipa-cmh commented
@livanov93 
Just ran some tests, works for me. 
Ill try to adapt https://github.com/ipa-cmh/prbt_robot to work with this.

2022-10-12 18:02 UTC, ipa-cmh commented
Okay have produced one working version here: https://github.com/ipa-cmh/prbt_robot_moveit_config
Great work.
One question the device controllers are only for a single device right? It would make sense having one that brings up the whole system or at least mutiple joints. Is that possible?

2022-10-13 09:05 UTC, ipa-cmh requested changes
Just one license issue.

2022-10-13 09:05 UTC, ipa-cmh commented on canopen_ros2_control/launch/cia402_system.launch.py
> +# Author: Lovro Ivanov lovro.ivanov@gmail.com
This should be Apache 2.0 no BSD

2022-10-14 06:27 UTC, ipa-cmh commented
@livanov93
Once these changes are made, we can merge this.

2022-10-19 05:48 UTC, merged

2022-10-20 05:24 UTC, destogl commented on canopen_ros2_control/launch/cia402_system.launch.py
> +# Author: Lovro Ivanov lovro.ivanov@gmail.com
@ipa-cmh ist the licence updated? If not we should do it.

2023-04-25 09:46 UTC, livanov93 commented
> ros2 topic pub /forward_position_controller/commands std_msgs/msg/Float64MultiArray "data:
> - 1.0"

Yes, you are correct here. Currently controllers support one device only. We can create multi-joint controllers which would expose all necessary topics and services per slave node on the bus.

2023-04-25 09:47 UTC, livanov93 commented
> Okay have produced one working version here: https://github.com/ipa-cmh/prbt_robot_moveit_config
> 
> Great work. One question the device controllers are only for a single device right? It would make sense having one that brings up the whole system or at least mutiple joints. Is that possible?


Yes, you are correct here. Currently controllers support one device only. We can create multi-joint controllers which would expose all necessary topics and services per slave node on the bus.